steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-layout-service:$BUILD_ID', './packages/layout-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/frontend-layout-service:$BUILD_ID', 'gcr.io/$PROJECT_ID/frontend-layout-service:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend-layout-service:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend-layout-service:$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment', 'frontend-layout-service', 'frontend-layout-service=gcr.io/$PROJECT_ID/frontend-layout-service:$BUILD_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=microfrontends-cluster'
tags: ['latest', '$BUILD_ID']
images: ['gcr.io/$PROJECT_ID/frontend-layout-service']