apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-header-fragment
  labels:
    app: frontend-header-fragment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-header-fragment
  template:
    metadata:
      labels:
        app: frontend-header-fragment
    spec:
      containers:
      - env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: PORT
          value: "8080"
        name: frontend-header-fragment
        image: gcr.io/microfrontends-armand1m/frontend-header-fragment
        ports:
        - containerPort: 3001

