apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-layout-service
  labels:
    app: frontend-layout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-layout-service
  template:
    metadata:
      labels:
        app: frontend-layout-service
    spec:
      containers:
      - env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: PORT
          value: "8080"
        name: frontend-layout-service
        image: gcr.io/microfrontends-armand1m/frontend-layout-service
        ports:
        - containerPort: 8080

