apiVersion: v1
kind: Service
metadata:
  name: frontend-layout-service
  labels:
    app: frontend-layout-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: frontend-layout-service
  selector:
    app: frontend-layout-service