steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-header-fragment:$BUILD_ID', './packages/header-fragment']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/frontend-header-fragment:$BUILD_ID', 'gcr.io/$PROJECT_ID/frontend-header-fragment:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend-header-fragment:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend-header-fragment:$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment', 'frontend-header-fragment', 'frontend-header-fragment=gcr.io/$PROJECT_ID/frontend-header-fragment:$BUILD_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=microfrontends-cluster'
tags: ['latest', '$BUILD_ID']
images: ['gcr.io/$PROJECT_ID/frontend-header-fragment']